# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Rocket.Chat Notification
        # You may pin to the exact commit or the version.
        # uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@2966f5f2e0313a94f965a51c08700cfecf0b6572
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        with:
          # job status (success, failure or cancelled)
          type: success
          # job name of workflow (format: markdown)
          job_name: Rocket.Chat notification
          # rocket.chat mention
          mention: # optional
          # the condition for mention
          mention_if: # optional
          # rocket.chat username
          username: # optional
          # rocket.chat icon emoji
          icon_emoji: # optional
          # rocket.chat channel
          channel: # optional
          # rocket.chat incoming webhook url
          url: https://chat.mousesoft.site/hooks/bjWHdASv6qDRCBuFq/96u7txwD9Gmz85HXPYKdErS7G3hbyAkHHLpgx3yisEpL4SYP
          # whether include commit data or not (true or false)
          commit: true
          # need to get commit data
          token: bjWHdASv6qDRCBuFq/96u7txwD9Gmz85HXPYKdErS7G3hbyAkHHLpgx3yisEpL4SYP
